kreait_firebase:
  projects:
    my_project:
      # Optional: Path to the project's Service Account credentials file
      # If omitted, the credentials will be auto-dicovered as described
      # in https://firebase-php.readthedocs.io/en/stable/setup.html#with-autodiscovery
      credentials: '%kernel.project_dir%/config/weCare.json'
      # Optional: If set to true, this project will be used when
      # type hinting the component classes of the Firebase SDK,
      # e.g. Kreait\Firebase\Auth, Kreait\Firebase\Database,
      # Kreait\Firebase\Messaging, etc.

